---
clair_scan_params: &clair_scan_params
  CLAIR_URL: {{HARBOR_URL}}
  CLAIR_PORT: {{CLAIR_PORT}}
  CLAIR_HEALTH_PORT: {{CLAIR_HEALTH_PORT}}
  CLAIR_IMAGE: {{APP_IMAGE}}
  CLAIR_INSECURE_REGISTRY: {{REPO_INSECURE_REGISTRY}}
  HARBOR_USERNAME: {{HARBOR_USERNAME}}
  HARBOR_PASSWORD: {{HARBOR_PASSWORD}}

notary_sign_params: &notary_sign_params
  HARBOR_URL: {{HARBOR_URL}}
  HARBOR_IMAGE: {{APP_REPO_IMAGE}}
  HARBOR_USERNAME: {{HARBOR_USERNAME}}
  HARBOR_PASSWORD: {{HARBOR_PASSWORD}}
  HARBOR_CA_CERT: {{HARBOR_CA_CERT}}
  NOTARY_ROOT_PASS: {{NOTARY_ROOT_PASS}}
  NOTARY_REPO_PASS: {{NOTARY_REPO_PASS}}

groups:
- name: HARBOR-FLOW
  jobs:
  - build-docker-image
  - cve-scan-harbor-image
  - sign-harbor-image

- name: K8S-FLOW
  jobs:
  - k8s-deployment


resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: virtmerlin/concourse-kubernetes-resource

resources:
- name: git-spring1-ci
  type: git
  source:
    uri: https://github.com/srinivasa-vasu/spring1-goapp-ci.git
    branch: master

- name: git-go-http
  type: git
  source:
    uri: https://github.com/tkrausjr/go-http
    branch: master

- name: harbor-image
  type: docker-image
  source:
    username: {{HARBOR_USERNAME}}
    password: {{HARBOR_PASSWORD}}
    repository: {{APP_REPO_IMAGE}}
    insecure_registries:
    - {{REPO_INSECURE_REGISTRY}}
    ca_certs: {{HARBOR_CA_CERT}}
    
- name: kubernetes-deployment
  type: kubernetes
  source:
    cluster_url: {{K8S_CLUSTER_URL}}
    namespace: {{K8S_NAMESPACE}}
    cluster_ca: {{K8S_CA_BASE64}}
    admin_user: {{K8S_ADMIN_USER}}
    admin_token: {{K8S_ADMIN_TOKEN}}
    resource_type: deployment
    resource_name: go-http
    resource_port: 8080
    overwrite: true

- name: kubernetes-service
  type: kubernetes
  source:
    cluster_url: {{K8S_CLUSTER_URL}}
    namespace: {{K8S_NAMESPACE}}
    cluster_ca: {{K8S_CA_BASE64}}
    admin_user: {{K8S_ADMIN_USER}}
    admin_token: {{K8S_ADMIN_TOKEN}}
    resource_type: service
    resource_name: svc-go-http
    overwrite: true

jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-go-http
    trigger: true
  - put: harbor-image
    params:
      build: git-go-http

- name: cve-scan-harbor-image
  plan:
  - aggregate:
    - get: git-spring1-ci
    - get: harbor-image
      passed: [build-docker-image]
      trigger: true
  - task: clair-scan-image
    file: git-spring1-ci/tasks/clair-scan-image/task.yml
    params: *clair_scan_params

- name: sign-harbor-image
  plan:
  - aggregate:
    - get: git-spring1-ci
    - get: harbor-image
      passed: [cve-scan-harbor-image]
      trigger: false
  - task: notary-sign-image
    privileged: true
    file: git-spring1-ci/tasks/notary-sign-image/task.yml
    params: *notary_sign_params

- name: k8s-deployment
  public: true
  serial: true
  plan:
  - get: harbor-image
    passed: [cve-scan-harbor-image]
    trigger: true
  - put: kubernetes-deployment
    params:
      image_name: {{APP_REPO_IMAGE}}
      #image_tag: latest
      port: 8080
  - put: kubernetes-service
    params:
      service_name: svc-go-http
      service_type: NodePort
      deployment_name: go-http
      service_port: 30001
      target_port: 8080
