---

platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

params:
  CLAIR_URL:
  CLAIR_PORT:
  CLAIR_HEALTH_PORT:
  CLAIR_IMAGE:
  CLAIR_INSECURE_REGISTRY:
  HARBOR_USERNAME:
  HARBOR_PASSWORD:


inputs:
  - name: git-src-repo

run:
  path: git-src-repo/tasks/clair-scan-image/task.sh
