---

platform: linux


image_resource:
  type: docker-image
  source: {repository: virtmerlin/docker-new}

params:
  HARBOR_USERNAME:
  HARBOR_PASSWORD:
  HARBOR_IMAGE:
  HARBOR_URL:
  HARBOR_CA_CERT:
  NOTARY_REPO_PASS:
  NOTARY_ROOT_PASS:

inputs:
  - name: git-spring1-ci

run:
  path: git-spring1-ci/tasks/notary-sign-image/task.sh
